spring.application.name=d-cart-backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


server.port=${PORT:8081}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update


#jwt.secret=myVeryStrongJWTSecretKey_ChangeThis_Atleast32Chars
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dproductions8228@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


info.app.name=Ecommerce Backend
info.app.version=1.0
info.app.developer=Dhanabal V






management.endpoints.web.exposure.include=*
management.endpoints.health.show-details=always
management.info.env.enabled=true
